# Generated by Django 5.1.1 on 2024-10-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin3App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
