# Generated by Django 5.1.1 on 2024-10-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin3App', '0002_rename_user_users'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
