# Generated by Django 5.1.1 on 2024-10-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin3App', '0003_alter_users_table'),
    ]

    operations = [
    ]
